version: '3.8'

services:
  superhands-frost:
    image: registry.urbreath.tech/superhands-frost:0.0.1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: superhands-frost
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always